### ISSUE TITLE
Godoc update breaks building

### ISSUE THREAD

**Issue by vansante** [davecheney/godoc2md#25]
A change was just done to golang/x/tools/godoc which breaks building this package unfortunately:

https://github.com/golang/tools/commit/e5fe289229602997ae560753d57bbbe888c1d34f

**Comment by thomasmodeneis** [comment]
Should work with `go1.10.1`.

**Comment by autodidaddict** [comment]
I just got this issue this morning on Go 1.11

```
go get github.com/davecheney/godoc2md
# github.com/davecheney/godoc2md
go/src/github.com/davecheney/godoc2md/main.go:173:6: pres.ShowExamples undefined (type *godoc.Presentation has no field or method ShowExamples)
go/src/github.com/davecheney/godoc2md/main.go:184:7: pres.PackageText undefined (type *godoc.Presentation has no field or method PackageText)
go/src/github.com/davecheney/godoc2md/main.go:186:7: pres.PackageText undefined (type *godoc.Presentation has no field or method PackageText)
go/src/github.com/davecheney/godoc2md/main.go:189:12: undefined: godoc.CommandLine
```

**Comment by morganhein** [comment]
Hey @autodidaddict, i'm unable to produce. Here are my steps showing it works:

`morgan $ git clone https://github.com/davecheney/godoc2md.git
Cloning into 'godoc2md'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 370 (delta 0), reused 1 (delta 0), pack-reused 369
Receiving objects: 100% (370/370), 91.74 KiB | 2.18 MiB/s, done.
Resolving deltas: 100% (176/176), done.
 morgan $ cd godoc2md/
 morgan $ go run .
usage: godoc2md package [name ...]
  -ex
    	show examples in command line mode
  -goroot string
    	Go root directory (default "/usr/lib/go")
  -hashformat string
    	source link URL hash format (default "#L%d")
  -links
    	link identifiers to their declarations (default true)
  -play
    	enable playground in web interface
  -srclink string
    	if set, format for entire source link
  -tabwidth int
    	tab width (default 4)
  -template string
    	path to an alternate template file
  -timestamps
    	show timestamps with directory listings
  -v	verbose mode
exit status 2`

**Comment by autodidaddict** [comment]
Turns out it was firewall related (I couldn't fetch dependencies). Now I just need to figure out what command line parameters to pass to get it to generate the docs for my root package ;)
